/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

package org.scalajs.testsuite.utils

/* This file is a stub used only by IDEs. The file used for actual compilation
 * is generated by the build.
 */

private[utils] object BuildInfo {
  final val scalaVersion = ""
  final val hasSourceMaps = false
  final val isNoModule = false
  final val isESModule = false
  final val isCommonJSModule = false
  final val usesClosureCompiler = false
  final val hasMinifiedNames = false
  final val compliantAsInstanceOfs = false
  final val compliantArrayIndexOutOfBounds = false
  final val compliantArrayStores = false
  final val compliantNegativeArraySizes = false
  final val compliantNullPointers = false
  final val compliantStringIndexOutOfBounds = false
  final val compliantModuleInit = false
  final val productionMode = false
  final val esVersion = 0
  final val useECMAScript2015Semantics = false
  final val isWebAssembly = false
  final val hasWasmCustomDescriptors = false
}
