package java.time

private[time] object Constants {
  final val NANOS_IN_MICRO = 1000

  final val MICROS_IN_MILLI = 1000

  final val NANOS_IN_MILLI = MICROS_IN_MILLI * NANOS_IN_MICRO

  final val MILLIS_IN_SECOND = 1000

  final val MICROS_IN_SECOND = MILLIS_IN_SECOND * MICROS_IN_MILLI

  final val NANOS_IN_SECOND = MILLIS_IN_SECOND * NANOS_IN_MILLI

  final val SECONDS_IN_MINUTE = 60

  final val MILLIS_IN_MINUTE = SECONDS_IN_MINUTE * MILLIS_IN_SECOND

  final val MICROS_IN_MINUTE = SECONDS_IN_MINUTE * MICROS_IN_SECOND

  final val NANOS_IN_MINUTE = SECONDS_IN_MINUTE * NANOS_IN_SECOND.toLong

  final val MINUTES_IN_HOUR = 60

  final val SECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTE

  final val MILLIS_IN_HOUR = MINUTES_IN_HOUR * MILLIS_IN_MINUTE

  final val MICROS_IN_HOUR = MINUTES_IN_HOUR * MICROS_IN_MINUTE.toLong

  final val NANOS_IN_HOUR = MINUTES_IN_HOUR * NANOS_IN_MINUTE

  final val HOURS_IN_DAY = 24

  final val MINUTES_IN_DAY = HOURS_IN_DAY * MINUTES_IN_HOUR

  final val SECONDS_IN_DAY = HOURS_IN_DAY * SECONDS_IN_HOUR

  final val MILLIS_IN_DAY = HOURS_IN_DAY * MILLIS_IN_HOUR

  final val MICROS_IN_DAY = HOURS_IN_DAY * MICROS_IN_HOUR

  final val NANOS_IN_DAY = HOURS_IN_DAY * NANOS_IN_HOUR

  final val SECONDS_IN_WEEK = SECONDS_IN_DAY * 7

  final val SECONDS_IN_MONTH = 2629746
}
