#! /bin/sh

SCALA_BIN_VER="@SCALA_BIN_VER@"
SCALAJS_VER="@SCALAJS_VER@"

BASE="$(dirname $0)/.."
CLILIB="$BASE/lib/scalajs-cli-assembly_$SCALA_BIN_VER-$SCALAJS_VER.jar"

scala -classpath "$CLILIB" org.scalajs.cli.Scalajsp "$@"
