/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

package org.scalajs.linker.testutils

/* This file is a stub used only by IDEs. The file used for actual compilation
 * is generated by the build.
 */

private[testutils] object StdlibHolder {
  final val minilib = ""
  final val javalib = ""
  final val previousLibs: Map[String, String] = Map.empty
}
