/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

package org.scalajs.core.tools.linker.backend.emitter

/* This file is a stub used only by IDEs. The file used for actual compilation
 * is generated by the build.
 */

private[emitter] object ScalaJSEnvHolder {
  final val scalajsenv = ""
}
